### ISSUE TITLE
Naming convention in Hexagonal architecture

### ISSUE THREAD

**Issue by ameghdadian** [bagashiz/go-pos#64]
Hi,

I took a look at your article about Hexagonal architecture, and I really appreciate your effort.

I was wondering If we could rename `CacheService` into `CacheRepository` since it's implemented inside the Adapter layer and the Core layer is using it?

```golang
type CacheService interface {
	// Set stores the value in the cache
	Set(ctx context.Context, key string, value []byte, ttl time.Duration) error
	// Get retrieves the value from the cache
	Get(ctx context.Context, key string) ([]byte, error)
	// Delete removes the value from the cache
	Delete(ctx context.Context, key string) error
	// DeleteByPrefix removes the value from the cache with the given prefix
	DeleteByPrefix(ctx context.Context, prefix string) error
	// Close closes the connection to the cache server
	Close() error
}
```

Is there a general rule in this architecture, stating that any interface provided by the Core layer should have a name ending with `Service` and anything else provided by the Adapter Layer to end with `Repository`? I'm specifically thinking about interfaces residing inside the Port directory.

**Comment by bagashiz** [comment]
Hello,

You're right, considering its direct interaction with the Redis database, renaming it to `CacheRepository` would be more fitting. I've been quite busy with college over the past month, but I plan to fix and improve the code during the upcoming holidays.

Thank you for your feedback!
