### ISSUE TITLE
Domain != Presentation 

### ISSUE THREAD

**Issue by e3nk0** [bagashiz/go-pos#65]
I really l liked your architecture - but intent of a domain is to be agnostic to outside world, and why do we have a key-word like json in the domain struct?
https://github.com/bagashiz/go-pos/blob/f17b11a84d98dd5c05a9f6fc788c2abfb722efa6/internal/core/domain/category.go#L7

**Comment by bagashiz** [comment]
Thanks for pointing that out, your feedback is much appreciated!

I initially added the json tag for potential API response handling but then I have since resolved this by creating a separate struct dedicated to API responses. I will remove it if it contradicts the domain's agnostic principle.
