### ISSUE TITLE
Migrate from paseto

### ISSUE THREAD

**Issue by 8thgencore** [bagashiz/go-pos#91]
Hi. You are using the [paseto](https://github.com/o1egl/paseto) library in your project, but it has not been supported for more than two years. It's not very safe, it's best to use another library.

**Comment by bagashiz** [comment]
I'll look into other alternative packages.

**Comment by 8thgencore** [comment]
maybe use https://github.com/golang-jwt/jwt?

**Comment by bagashiz** [comment]
I'm leaning towards PASETO instead of JWT, there is a good discourse on Reddit about this topic recently: https://www.reddit.com/r/golang/comments/1aeurc0/comment/kkaurej

But feel free to contribute by submitting a pull request!

**Comment by 8thgencore** [comment]
paseto looks very interesting. you can switch to https://github.com/aidantwoods/go-paseto, at least this project is actively supported
